name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:  
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan 
      run: bandit -ll -ii -r . -f json -o sast-report.json
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()  
      with:
         name: sast-findings
         path: sast-report.json
  
  sca_scan:
    name: Run Safety SCA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:  
        python-version: 3.8
    
    - name: Install Safety
      run: pip install safety
    
    - name: Run Safety Scan
      run: safety check -r requirements.txt --output json > safety-report.json
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()  
      with:
         name: safety-findings
         path: safety-report.json